language: php

arch: amd64
os:   linux
dist: xenial

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

jobs:
    fast_finish: true
    allow_failures:
        - php: nightly

services:
    - mysql
    - postgresql

install:
    - composer self-update --2
    - composer install

before_script:
    - mysql -e "create database IF NOT EXISTS test_db;" -uroot
    - psql -c 'create database test_db;' -U postgres

script:
    -  php -d 'xdebug.mode=coverage' vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        recipients:
            - poisoncorpsee@gmail.com

        on_success: always
        on_failure: always
