language: php

arch: amd64
os:   linux
dist: xenial

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

jobs:
    fast_finish: true

services:
    - mysql
    - postgresql

install:
    - composer self-update --2
    - composer install

script:
    -  php -d 'xdebug.mode=coverage' vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        recipients:
            - poisoncorpsee@gmail.com

        on_success: always
        on_failure: always
