coverage:
    round: nearest
    precision: 2

github_checks:
    annotations: false

comment: false

ignore:
    - "app"
    - "docs"
    - "public"
    - "runtime"
    - "tests"
    - "vendor"
    - "src/Migrations"
    - "src/Languages"
