b8:
  database:
    servers:
      read:  localhost
      write: localhost
    port:     3306
    name:     php-censor-db
    username: php-censor-user
    password: php-censor-password
php-censor:
  url: 'http://php-censor.local'
  worker:
    host:  localhost
    queue: php-censor-queue
